# Generated by Django 2.2 on 2020-03-27 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='model_text',
            new_name='status_text',
        ),
    ]
